import WebSocket from 'ws';
const BASE = process.env.BASE, TOKEN = process.env.TOKEN, ORIGIN = 'https://svnz-portweb.vicemi.dev';
const api = (p, o={}) => fetch(BASE+p, {...o, headers:{'content-type':'application/json','x-svnz-token':TOKEN, origin: ORIGIN}}).then(async r=>({s:r.status, j:await r.json().catch(()=>({}))}));
const wsurl = BASE.replace(/^http/,'ws')+'/ws';
const open = () => new Promise((res,rej)=>{ const w=new WebSocket(wsurl,['svnz-v1','token.'+TOKEN],{headers:{origin:ORIGIN}}); w.on('open',()=>res(w)); w.on('error',rej); w.on('unexpected-response',(_q,r)=>rej(new Error('http '+r.statusCode))); });
const T0=Date.now();
const info = await api('/api/info'); console.log('info', info.s, info.j.protocol);
const r = await api('/api/rooms',{method:'POST',body:JSON.stringify({mode:'coop'})}); console.log('create', r.s, r.j.code);
const host = await open(), guest = await open();
const inbox = {h:[], g:[]}; host.on('message',d=>inbox.h.push(JSON.parse(d))); 
const gs=[]; let closed={h:null,g:null}; host.on('close',(c,r)=>{closed.h=[c,String(r),Math.round((Date.now()-T0)/1000)]}); guest.on('close',(c,r)=>{closed.g=[c,String(r),Math.round((Date.now()-T0)/1000)]});
guest.on('message',d=>{ const m=JSON.parse(d); inbox.g.push(m); if(m.t==='snap') gs.push([Date.now(), m.d.q]); });
host.send(JSON.stringify({t:'join',code:r.j.code,name:'Host',key:r.j.hostKey}));
await new Promise(r=>setTimeout(r,800));
guest.send(JSON.stringify({t:'join',code:r.j.code,name:'Guest'}));
await new Promise(r=>setTimeout(r,800));
guest.send(JSON.stringify({t:'ready',ready:true}));
await new Promise(r=>setTimeout(r,500));
host.send(JSON.stringify({t:'start'}));
await new Promise(r=>setTimeout(r,800));
setInterval(()=>{ try{ guest.send(JSON.stringify({t:'in',d:{m:8,tp:1}})); }catch{} }, 100);
const N = Number(process.env.SECS||20)*30; let q=0; const t0=Date.now();
const big = Array.from({length:12},(_,i)=>({u:i,k:'DemonNinja',s:1,tm:2,n:'Enemy'+i,sl:-1,x:100.5,y:0,z:90.2,f:1,a:10,r:3,l:100,m:100,p:0,b:2,bt:[0,0,0,0,0],sk:0,bf:0}));
await new Promise(res=>{ const iv=setInterval(()=>{ host.send(JSON.stringify({t:'snap',d:{q:q++, fs:big}})); if(q>=N){clearInterval(iv);res();} }, 1000/30); });
await new Promise(r=>setTimeout(r,1500));
const gaps=gs.slice(1).map((x,i)=>x[0]-gs[i][0]); gaps.sort((a,b)=>a-b);
console.log('sent',N,'received',gs.length,'in',((Date.now()-t0)/1000).toFixed(1)+'s','median gap',gaps[gaps.length>>1],'p95',gaps[Math.floor(gaps.length*.95)],'max',gaps[gaps.length-1], 'closed',JSON.stringify(closed));
const missing = new Set(gs.map(x=>x[1])); let lost=0; for(let i=0;i<N;i++) if(!missing.has(i)) lost++; console.log('lost',lost);
host.close(); guest.close(); process.exit(0);
